
CREATE TABLE users (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    address TEXT NOT NULL,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE books (
    ID INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY(ID),
    title TEXT NOT NULL,
    author VARCHAR(100) NOT NULL,
    release_date DATE NOT NULL,
    lang VARCHAR(30),
    price INT UNSIGNED NOT NULL,
    pages INT UNSIGNED NOT NULL,
    purchase_date DATE NOT NULL,
    gift BOOLEAN NOT NULL,
    credit_card BOOLEAN NOT NULL,
    cash BOOLEAN NOT NULL 
);

CREATE TABLE users_books (
	ID INT NOT NULL AUTO_INCREMENT,
    fk_userId INT UNSIGNED NOT NULL,
    fk_bookId INT UNSIGNED NOT NULL,
    
    PRIMARY KEY(ID),
    INDEX (fk_userId),
    INDEX (fk_bookId),
    
    FOREIGN KEY (fk_userId)
    	REFERENCES users.ID,
    
    FOREIGN KEY (fk_bookId)
    	REFERENCES books.ID
);
